server.document-root = "/useremain/rinkhals/.current/home/rinkhals/apps/fluidd/fluidd"
server.port = 4408

server.modules  =  (
   "mod_proxy"
)

index-file.names = ( "index.html" )

mimetype.assign = (
  ".html" => "text/html",
  ".js" => "text/javascript",
  ".css" => "text/css"
)

$HTTP["url"] =~ "^/websocket" {
  proxy.server = ( "" => ( ( "host" => "127.0.0.1", "port" => 7125 ) ) )
  proxy.header = ( "upgrade" => "enable" )
}
$HTTP["url"] =~ "^/(printer|api|access|machine|server)" {
  proxy.server = ( "" => ( ( "host" => "127.0.0.1", "port" => 7125 ) ) )
}
$HTTP["url"] =~ "^/webcam" {
  proxy.server = ( "" => ( ( "host" => "127.0.0.1", "port" => 8080 ) ) )
}
