name: Build base images

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - build/1-buildroot/**
      - build/1-luckfox/**

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: "Buildroot: Build"
      uses: docker/build-push-action@v6
      with:
        file: build/1-buildroot/builder.Dockerfile
        pull: true
        push: true
        tags: ghcr.io/${{ github.repository }}/buildroot-builder:${{ github.sha::7 }}

    - name: "Buildroot: Extract rootfs"
      working-directory: ./docs
      run: docker run --rm -it -v .\tmp:/tmp -v .\build:/build ghcr.io/${{ github.repository }}/buildroot-builder:${{ github.sha::7 }} /build/1-buildroot/extract-rootfs.sh

    - name: "Buildroot: Prepare image"
      uses: docker/build-push-action@v6
      with:
        file: build/1-buildroot/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/buildroot-base

    - name: "Luckfox: Build"
      uses: docker/build-push-action@v6
      with:
        file: build/1-luckfox/builder.Dockerfile
        pull: true
        push: true
        tags: ghcr.io/${{ github.repository }}/luckfox-builder:${{ github.sha::7 }}

    - name: "Luckfox: Extract rootfs"
      working-directory: ./docs
      run: docker run --rm -it -v .\tmp:/tmp -v .\build:/build ghcr.io/${{ github.repository }}/luckfox-builder:${{ github.sha::7 }} /build/1-luckfox/extract-rootfs.sh

    - name: "Luckfox: Prepare image"
      uses: docker/build-push-action@v6
      with:
        file: build/1-luckfox/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/luckfox-base
